# Generated by Django 5.0.1 on 2024-04-18 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('idCaja', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=20)),
                ('monto', models.FloatField()),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('idClase', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('dia', models.CharField(max_length=10)),
                ('horario', models.CharField(max_length=15)),
                ('fecha', models.DateField()),
                ('costoCuotas', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idCliente', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Entrenador',
            fields=[
                ('idEntrenador', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('idProducto', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('stock', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='clientesXclases',
            fields=[
                ('idCxC', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('estado', models.CharField(max_length=30)),
                ('idClase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Academico.clase')),
                ('idCliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Academico.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Cobro',
            fields=[
                ('idCobro', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('CostoCuota', models.FloatField()),
                ('fecha', models.DateField()),
                ('idClase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Academico.clase')),
                ('idCliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Academico.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Facturas',
            fields=[
                ('numFac', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombreFac', models.CharField(max_length=20)),
                ('fecha', models.DateField()),
                ('importe', models.FloatField()),
                ('idCaja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Academico.caja')),
            ],
        ),
        migrations.CreateModel(
            name='Recibos',
            fields=[
                ('numRecibo', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('sueldo', models.FloatField()),
                ('fecha', models.DateField()),
                ('idEntrenador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Academico.entrenador')),
            ],
        ),
        migrations.CreateModel(
            name='Rutinas',
            fields=[
                ('idRutina', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('ejercicio', models.CharField(max_length=20)),
                ('cantidad', models.IntegerField()),
                ('fecha', models.DateField()),
                ('idCliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Academico.cliente')),
                ('idEntrenador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Academico.entrenador')),
            ],
        ),
    ]
