# Generated by Django 5.0.1 on 2024-08-14 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='alumnoXclase',
            fields=[
                ('idAxC', models.CharField(max_length=6, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='clase',
            name='dia',
            field=models.CharField(max_length=50),
        ),
    ]
